"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'

import _payments_page from './payments-page.bones.json'
import _book_service from './book-service.bones.json'
import _family_page from './family-page.bones.json'
import _parent_bookings from './parent-bookings.bones.json'
import _parent_dashboard_returning from './parent-dashboard-returning.bones.json'
import _support_page from './support-page.bones.json'

registerBones({
  "payments-page": _payments_page,
  "book-service": _book_service,
  "family-page": _family_page,
  "parent-bookings": _parent_bookings,
  "parent-dashboard-returning": _parent_dashboard_returning,
  "support-page": _support_page,
})
